### ISSUE TITLE
How do I log into management portal to execute sql query?

### ISSUE THREAD

**Issue by sharemedics** [intersystems-community/iris-fhir-template#10]
Do you know how I can login into execute sql query? When I get to http://localhost:32783/csp/sys/exp/%25CSP.UI.Portal.SQL.Home.zen?$NAMESPACE=FHIRSERVER&$NAMESPACE=FHIRSERVER, I get a prompt to enter a username/password. I am using _SYSTEM/SYS but that does not appear to be work

**Comment by evshvarov** [comment]
docker system prune -fhi!
the link works for me, just built the docker image and tested it.
[image: Screenshot 2020-08-16 at 10.28.11.png]
Could you try to increase docker resources (space?) or make a docker clean
up with:
docker system prune -f

**Comment by sharemedics** [comment]
I tried to make a clean docker instance but am still not able to log into
the management portal.

Also, your screenshot did not come through.

**Comment by sharemedics** [comment]
Hello again, I was able to figure it out. It looks like I was using the
wrong URL to login. I am good now.
